# Generated by Django 3.1.3 on 2020-12-22 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=3)),
                ("seasons", models.IntegerField()),
                ("appearances", models.IntegerField()),
                ("goals", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("average_rating", models.FloatField()),
                ("pom", models.IntegerField()),
                ("reds", models.IntegerField()),
                ("yellows", models.IntegerField()),
                ("positions", models.CharField(max_length=30)),
                ("max_value", models.FloatField()),
                ("home_grown_status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Save",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team", models.CharField(max_length=150)),
                ("date", models.DateField(auto_now_add=True)),
                ("seasons", models.IntegerField(default=0)),
                ("currency", models.CharField(max_length=5)),
                ("height_choice", models.CharField(max_length=3)),
                ("wage_period", models.CharField(max_length=5)),
                ("distance_choice", models.CharField(max_length=5)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_year", models.IntegerField()),
                ("divison", models.IntegerField()),
                ("position", models.IntegerField()),
                ("notes", models.TextField()),
                (
                    "save",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.save"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerSeason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("wage", models.IntegerField()),
                ("playing_time", models.CharField(max_length=150)),
                ("determination", models.IntegerField()),
                ("teamwork", models.IntegerField()),
                ("leadership", models.IntegerField()),
                ("appearances", models.IntegerField()),
                ("minutes", models.IntegerField()),
                ("average_rating", models.FloatField()),
                ("pom", models.IntegerField()),
                ("goals", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("reds", models.IntegerField()),
                ("yellows", models.IntegerField()),
                ("clean_sheets", models.IntegerField()),
                ("conceded", models.IntegerField()),
                ("goal_mistakes", models.IntegerField()),
                ("header_percent", models.IntegerField()),
                ("int_per_90", models.FloatField()),
                ("tackles", models.IntegerField()),
                ("tackle_ratio", models.FloatField()),
                ("cr_c", models.IntegerField()),
                ("dist_per_90", models.FloatField()),
                ("dribbles", models.IntegerField()),
                ("pass_completion", models.FloatField()),
                ("key_passes", models.IntegerField()),
                ("penalties", models.IntegerField()),
                ("xG", models.FloatField()),
                ("shots", models.IntegerField()),
                ("shot_percent", models.IntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.player"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.season"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="save",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainApp.save"
            ),
        ),
    ]
