# Generated by Django 3.1.3 on 2020-12-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="season",
            old_name="divison",
            new_name="division",
        ),
    ]
