# Generated by Django 3.1.3 on 2020-12-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20201225_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='save',
            new_name='game_save',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='save',
            new_name='game_save',
        ),
    ]
