# Generated by Django 3.1.3 on 2020-12-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_auto_20201225_0722"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerseason",
            name="value",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
