# Generated by Django 3.1.3 on 2020-12-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20201226_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='wage_period',
            field=models.CharField(max_length=10),
        ),
    ]
