# Generated by Django 3.1.3 on 2020-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0009_season_teams_in_league"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
