# Generated by Django 3.1.3 on 2020-12-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20201227_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists_per_90',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_per_90',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='minutes_per_season',
            field=models.FloatField(default=0),
        ),
    ]
