# Generated by Django 3.1.3 on 2020-12-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20201228_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseason',
            name='assists_per_90',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerseason',
            name='goals_per_90',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
