# Generated by Django 3.1.3 on 2020-12-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0014_auto_20201229_0250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="shot_percent",
            field=models.IntegerField(default=0),
        ),
    ]
