# Generated by Django 3.1.3 on 2021-01-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0015_auto_20201229_0252"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="save",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="save",
            name="distance_choice",
        ),
        migrations.RemoveField(
            model_name="save",
            name="height_choice",
        ),
        migrations.RemoveField(
            model_name="save",
            name="wage_period",
        ),
    ]
